In [24]:
# using python lists or tuples
import numpy as np

lst = [1, 2, 3]
my_array = np.array(lst)
my_array

array([1, 2, 3])

In [25]:
# using numpy functions
zeros_array= np.zeros((3,3))
print(zeros_array)

ones_array=np.ones((2,4))
ones_array

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# array indexing and slicing:accessing elements:
my_array=np.array([2,3,4,5,6])
print(int(my_array[2]))

slice = my_array[1:4]
slice

4


array([3, 4, 5])

In [27]:
# performing element-wise operations on arrays:
arr1= np.array([1,2,3,4])
arr2= np.array([5,6,7,8])

arr= arr1+ arr2
arr

array([ 6,  8, 10, 12])

In [28]:
# linear algebra operations

arr1= np.array([1,2,3,4])
arr2= np.array([5,6,7,8])

arr= int(np.dot(arr1,arr2))
arr

70