In [11]:
# Using Python lists or tuples
import numpy as np

lst= [1,2,3]
my_array= np.array(lst)
my_array

array([1, 2, 3])

In [12]:
# Using numpy functions

zeros_array= np.zeros((2,3))
zeros_array

ones_array= np.ones((2,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# Array indexing and slicing:Accessing elements:
my_array= np.array([2,3,4,5,6])

print(my_array[2])

slice= my_array[1:]
slice



4


array([3, 4, 5, 6])

In [14]:
# Performing element-wise operations on arrays:
arr1= np.array([2,3,4,5])
arr2= np.array([8,9,10,11])

arr= arr1+arr2
arr


array([10, 12, 14, 16])

In [15]:
# Linear Algebra Operations
arr1= np.array([2,3,4,5])
arr2= np.array([8,9,10,11])

arr= np.dot(arr1, arr2)
arr


np.int64(138)

In [16]:
2*8 +3*9+4*10+5*11

138